# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!



target 'webviewapp' do
pod 'Firebase/Core'
pod 'Firebase/Messaging'

end

target 'webviewappTests' do

end

target 'webviewappUITests' do

end

